### ISSUE TITLE
Trouble with ts-node on react native - Cannot use import outside a module

### ISSUE THREAD

**Issue by LeoRedin** [webdriverio/appium-boilerplate#118]
**Describe your question with as much detail as possible**
Howdy! I think I have config problem, all the tests run fine, except when I import a file from my actual source code. Here's the folder structure we have right now is below(sorry I don't know how to create that beautiful tree) but the e2e and src folder are on the same level and I am importing my strings from localization and using inside the e2e test, my selectors come from the same place.

|-- e2e
|---- login.spec.ts
|-- src
|---- localization
|------ index.ts
|-- tsconfig.json

**If it's about a specific piece of code, try and include some of it to support your question.**

_ts-node_
```js
{
  "compilerOptions": {
    "target": "esnext" ,
    "module": "commonjs" ,
    "lib": ["es6"] ,
    "allowJs": true ,
    "sourceMap": true ,
    "noEmit": true ,
    "isolatedModules": true ,
    "skipLibCheck": true,
    "strict": true ,
    "moduleResolution": "node" ,
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "types": ["node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio", "jest"]
  },
  "exclude": ["node_modules", "babel.config.js", "metro.config.js", "jest.config.js"]
}
```
_babel.config.js_
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset', '@babel/preset-typescript'],
  plugins: [
    [
      'module-resolver',
      {
        extensions: [
          '.js',
          '.jsx',
          '.ts',
          '.tsx',
          '.android.js',
          '.android.tsx',
          '.ios.js',
          '.ios.tsx',
        ],
        root: ['./src'],
      },
    ],
  ],
};
```
_WelcomeScreen.ts_
```js
import { Strings } from './../../../src/localization/';

import AppScreen from './AppScreen';

class WelcomeScreen extends AppScreen {
  constructor() {
    super('~Welcome-screen');
  }

  private get letsGoButton() {
    return $(`~${Strings.lets_go_button}`);
  }

  async tapOnLetsGoButton() {
    await this.letsGoButton.click();
  }
}

export default new WelcomeScreen();
```

_config.ts_
```js
export const config: WebdriverIO.Config = {
  runner: 'local',
  maxInstances: 1,
  specs: [],
  capabilities: [],
  logLevel: 'trace',
  bail: 0,
  baseUrl: 'http://localhost',
  waitforTimeout: 45000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 3 * 60 * 1000, // 3min
  },
};
```

The error I am getting:
2021-12-02T21:32:06.768Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): /Users/leonardo.redin/Projects/apppath/app/e2e/tests/specs/login.spec.ts
[0-0] Error: /Users/leonardo.redin/Projects/apppath/app/node_modules/react-native/index.js:14
[0-0] import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
[0-0] ^^^^^^
[0-0] 
[0-0] SyntaxError: Cannot use import statement outside a module
[0-0]     at wrapSafe (internal/modules/cjs/loader.js:979:16)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1027:27)
[0-0]     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0-0]     at Object.require.extensions.<computed> [as .js] (/Users/leonardo.redin/Projects/apppath/app/node_modules/ts-node/src/index.ts:1355:43)
[0-0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0-0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0-0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0-0]     at require (internal/modules/cjs/helpers.js:88:18)
[0-0]     at Object.<anonymous> (/Users/leonardo.redin/Projects/apppath/app/node_modules/react-native-localization/lib/LocalizedStrings.js:20:20)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Environment (please complete the following information):**
 - Node.js version: 14.16.1
 - NPM version:6.14.12
 - Platform: iOS
 - Platform version: 15.0
 - Emulator/Simulator/Real Device: Simulator

**Additional context**
As I could see I can run the ```tsc``` command and the app, everything that is inside the ```src``` folder is ok but when importing that file into the ```e2e``` folder makes things break. Maybe I am missing some configuration? Thanks for any help!

**Comment by wswebcreation** [comment]
@LeoRedin 

Am I understanding it correctly that you use TypeScript and JS (both TS and Babel compilers) at the same time?

**Comment by LeoRedin** [comment]
Yeah, as far as I can tell we do use both. I am new to this project and I am trying to setup this e2e tooling. But seeing the logs of webdrive it detects that I have tá-node and is probably trying to use?

**Comment by wswebcreation** [comment]
Tbh, I never used TS and Babel in one project. I don't have a straightforward answer for you, sorry.

**Comment by samuelfreiberg** [comment]
@LeoRedin How did you solve this issue?

**Comment by LeoRedin** [comment]
> 

The problem itself was mainly on using some code that never got transpiled, so we took it out. In our case the strings object used some react native lib and we split the strings into a plain ts file and then the code that actually built all the localized strings. We didn't spend too much time trying to solve the configs in the project. 
Sorry I couldn't help you more
