### ISSUE TITLE
ios.app webview flacky tests fail on ios platform 15.5 and iPhone 12

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/appium-boilerplate#133]
**Environment (please complete the following information):**
 - Node.js version: 18.12.1
 - NPM version: yarn 1.22.17
 - Platform: iOS
 - Platform version: 15.5
 - Emulator/Simulator/Real Device: Simulatoir

**Describe the bug**

1st launch:

```
 "spec" Reporter:
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-0] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-0] Session ID: 13ab74f0-8d2f-4214-b235-fca01a4d80c4
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] » /tests/specs/app.biometric.login.spec.ts
[iPhone 12 iOS 15.5 #0-0] WebdriverIO and Appium, when interacting with a biometric button,
[iPhone 12 iOS 15.5 #0-0]    ✓ should be able to login with a matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0]    ✖ should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] 1 passing (27.4s)
[iPhone 12 iOS 15.5 #0-0] 1 failing
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] 1) WebdriverIO and Appium, when interacting with a biometric button, should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0] An attempt was made to operate on a modal dialog when one was not open
[iPhone 12 iOS 15.5 #0-0] no such alert: An attempt was made to operate on a modal dialog when one was not open
[iPhone 12 iOS 15.5 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 12 iOS 15.5 #0-0]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.biometric.login.spec.ts:66:26)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-1] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-1] Session ID: 2ecd9ff9-01c2-48d6-b152-3ff43d1c71e9
[iPhone 12 iOS 15.5 #0-1]
[iPhone 12 iOS 15.5 #0-1] » /tests/specs/app.deep.link.navigation.spec.ts
[iPhone 12 iOS 15.5 #0-1] WebdriverIO and Appium, when navigating by deep link
[iPhone 12 iOS 15.5 #0-1]    ✖ should be able to open the webview
[iPhone 12 iOS 15.5 #0-1]    ✓ should be able to open the login form screen
[iPhone 12 iOS 15.5 #0-1]    ✓ should be able to open the forms screen
[iPhone 12 iOS 15.5 #0-1]    ✓ should be able to open the swipe screen
[iPhone 12 iOS 15.5 #0-1]    ✓ should be able to open the drag and drop screen
[iPhone 12 iOS 15.5 #0-1]    ✓ should be able to open the home screen
[iPhone 12 iOS 15.5 #0-1]
[iPhone 12 iOS 15.5 #0-1] 5 passing (1m 9.7s)
[iPhone 12 iOS 15.5 #0-1] 1 failing
[iPhone 12 iOS 15.5 #0-1]
[iPhone 12 iOS 15.5 #0-1] 1) WebdriverIO and Appium, when navigating by deep link should be able to open the webview
[iPhone 12 iOS 15.5 #0-1] Webview context not loaded
[iPhone 12 iOS 15.5 #0-1] Error: Webview context not loaded
[iPhone 12 iOS 15.5 #0-1]     at async WebViewScreen.waitForWebViewContextLoaded (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/helpers/WebView.ts:26:9)
[iPhone 12 iOS 15.5 #0-1]     at async WebViewScreen.waitForWebsiteLoaded (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/helpers/WebView.ts:80:9)
[iPhone 12 iOS 15.5 #0-1]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.deep.link.navigation.spec.ts:17:9)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-2] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-2] Session ID: fb937115-5c82-409f-85a7-9d9058c98ea9
[iPhone 12 iOS 15.5 #0-2]
[iPhone 12 iOS 15.5 #0-2] » /tests/specs/app.drag.and.drop.spec.ts
[iPhone 12 iOS 15.5 #0-2] WebdriverIO and Appium, when using drag and drop
[iPhone 12 iOS 15.5 #0-2]    ✓ should be able to solve the puzzle by dragging the pieces into the puzzle
[iPhone 12 iOS 15.5 #0-2]
[iPhone 12 iOS 15.5 #0-2] 1 passing (24.7s)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-3] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-3] Session ID: 38d39a0c-0bf1-4189-b2ee-66a78c452051
[iPhone 12 iOS 15.5 #0-3]
[iPhone 12 iOS 15.5 #0-3] » /tests/specs/app.forms.spec.ts
[iPhone 12 iOS 15.5 #0-3] WebdriverIO and Appium, when interacting with form elements,
[iPhone 12 iOS 15.5 #0-3]    ✓ should be able type in the input and validate the text
[iPhone 12 iOS 15.5 #0-3]    ✓ should be able turn on and off the switch
[iPhone 12 iOS 15.5 #0-3]    ✓ should be able select a value from the select element
[iPhone 12 iOS 15.5 #0-3]    ✓ should be able to open the alert and close it with all 3 buttons
[iPhone 12 iOS 15.5 #0-3]    ✓ should be able to determine that the inactive button is inactive
[iPhone 12 iOS 15.5 #0-3]
[iPhone 12 iOS 15.5 #0-3] 5 passing (29.8s)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-4] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-4] Session ID: 5622d584-4f91-4af4-bdd2-a57192647f51
[iPhone 12 iOS 15.5 #0-4]
[iPhone 12 iOS 15.5 #0-4] » /tests/specs/app.login.spec.ts
[iPhone 12 iOS 15.5 #0-4] WebdriverIO and Appium, when interacting with a login form,
[iPhone 12 iOS 15.5 #0-4]    ✓ should be able login successfully
[iPhone 12 iOS 15.5 #0-4]    ✓ should be able sign up successfully
[iPhone 12 iOS 15.5 #0-4]
[iPhone 12 iOS 15.5 #0-4] 2 passing (24.8s)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-5] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-5] Session ID: b554593c-d083-42d7-833c-f5a3d2931ee9
[iPhone 12 iOS 15.5 #0-5]
[iPhone 12 iOS 15.5 #0-5] » /tests/specs/app.swipe.spec.ts
[iPhone 12 iOS 15.5 #0-5] WebdriverIO and Appium, when using swiping
[iPhone 12 iOS 15.5 #0-5]    ✓ should be able to swipe horizontal by swiping the carousel from left to right
[iPhone 12 iOS 15.5 #0-5]    ✓ should be able to swipe vertical by finding the surprise
[iPhone 12 iOS 15.5 #0-5]
[iPhone 12 iOS 15.5 #0-5] 2 passing (37.6s)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-6] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-6] Session ID: 7545aef4-eb24-4082-b06e-606419718dc7
[iPhone 12 iOS 15.5 #0-6]
[iPhone 12 iOS 15.5 #0-6] » /tests/specs/app.tab.bar.navigation.spec.ts
[iPhone 12 iOS 15.5 #0-6] WebdriverIO and Appium, when using navigation through the tab bar
[iPhone 12 iOS 15.5 #0-6]    ✖ should be able to open the webview
[iPhone 12 iOS 15.5 #0-6]    ? should be able to open the login form screen
[iPhone 12 iOS 15.5 #0-6]    ✖ "before each" hook for WebdriverIO and Appium, when using navigation through the tab bar
[iPhone 12 iOS 15.5 #0-6]
[iPhone 12 iOS 15.5 #0-6] 2 failing (29.7s)
[iPhone 12 iOS 15.5 #0-6]
[iPhone 12 iOS 15.5 #0-6] 1) WebdriverIO and Appium, when using navigation through the tab bar should be able to open the webview
[iPhone 12 iOS 15.5 #0-6] Website not loaded
[iPhone 12 iOS 15.5 #0-6] Error: Website not loaded
[iPhone 12 iOS 15.5 #0-6]     at async WebViewScreen.waitForDocumentFullyLoaded (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/helpers/WebView.ts:62:9)
[iPhone 12 iOS 15.5 #0-6]     at async WebViewScreen.waitForWebsiteLoaded (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/helpers/WebView.ts:82:9)
[iPhone 12 iOS 15.5 #0-6]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.tab.bar.navigation.spec.ts:16:9)
[iPhone 12 iOS 15.5 #0-6]
[iPhone 12 iOS 15.5 #0-6] 2) WebdriverIO and Appium, when using navigation through the tab bar "before each" hook for WebdriverIO and Appium, when using navigation through the tab bar
[iPhone 12 iOS 15.5 #0-6] An unknown server-side error occurred while processing the command. Original error: Unsupported locator strategy: accessibility id
[iPhone 12 iOS 15.5 #0-6] unknown error: An unknown server-side error occurred while processing the command. Original error: Unsupported locator strategy: accessibility id
[iPhone 12 iOS 15.5 #0-6]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 12 iOS 15.5 #0-6]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.tab.bar.navigation.spec.ts:11:9)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-7] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-7] Session ID: f1c5de9f-c47d-4796-9e25-e5e9a65993ab
[iPhone 12 iOS 15.5 #0-7]
[iPhone 12 iOS 15.5 #0-7] » /tests/specs/app.webview.spec.ts
[iPhone 12 iOS 15.5 #0-7] WebdriverIO and Appium, when interacting with a WebView,
[iPhone 12 iOS 15.5 #0-7]    ✖ should be able to switch between webview, native and webview
[iPhone 12 iOS 15.5 #0-7]
[iPhone 12 iOS 15.5 #0-7] 1 failing (1m 21s)
[iPhone 12 iOS 15.5 #0-7]
[iPhone 12 iOS 15.5 #0-7] 1) WebdriverIO and Appium, when interacting with a WebView, should be able to switch between webview, native and webview
[iPhone 12 iOS 15.5 #0-7] element (".DocSearch-Input") still not displayed after 45000ms
[iPhone 12 iOS 15.5 #0-7] Error: element (".DocSearch-Input") still not displayed after 45000ms
[iPhone 12 iOS 15.5 #0-7]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.webview.spec.ts:63:9)
------------------------------------------------------------------
[iPhone 12 iOS 15.5 #0-8] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-8] Session ID: ab4cb180-d763-4530-b775-ef61f9eb2553
[iPhone 12 iOS 15.5 #0-8]
[iPhone 12 iOS 15.5 #0-8] » /tests/specs/app.webview.xpath.spec.ts
[iPhone 12 iOS 15.5 #0-8] WebdriverIO and Appium, when interacting with a webview through XPATH
[iPhone 12 iOS 15.5 #0-8]    ✓ should be able to verify that the WebView is shown by xpath
[iPhone 12 iOS 15.5 #0-8]    ✓ should be able to verify that the WebView is shown by switching to the WebView
[iPhone 12 iOS 15.5 #0-8]
[iPhone 12 iOS 15.5 #0-8] 2 passing (30.3s)


Spec Files:	 5 passed, 4 failed, 9 total (100% completed) in 00:10:16 

```

2nd launch:

```
[iPhone 12 iOS 15.5 #0-0] Running: iPhone 12 on iOS 15.5 executing /Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 12 iOS 15.5 #0-0] Session ID: f709c7e4-73eb-4f9b-9d95-036937149b75
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] » /tests/specs/app.biometric.login.spec.ts
[iPhone 12 iOS 15.5 #0-0] WebdriverIO and Appium, when interacting with a biometric button,
[iPhone 12 iOS 15.5 #0-0]    ✓ should be able to login with a matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0]    ✖ should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] 1 passing (18s)
[iPhone 12 iOS 15.5 #0-0] 1 failing
[iPhone 12 iOS 15.5 #0-0]
[iPhone 12 iOS 15.5 #0-0] 1) WebdriverIO and Appium, when interacting with a biometric button, should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 12 iOS 15.5 #0-0] An attempt was made to operate on a modal dialog when one was not open
[iPhone 12 iOS 15.5 #0-0] no such alert: An attempt was made to operate on a modal dialog when one was not open
[iPhone 12 iOS 15.5 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 12 iOS 15.5 #0-0]     at async Context.<anonymous> (/Users/dka/workspace/github.com/kopax-polyconseil/appium-boilerplate/tests/specs/app.biometric.login.spec.ts:66:26)
```

**To Reproduce**

- clone repo
- edit `config/wdio.ios.app.conf.ts` capabilities with `appium:deviceName=iPhone 12` `appium:platformVersion=15.5`
- `yarn force; yarn ios.app`

**Expected behavior**

As a boilerplate, we expect test to pass

**Comment by christian-bromann** [comment]
Thanks for reporting @kopax-polyconseil 

Any contributions to resolve this bug are much appreciated. Thanks!

**Comment by christian-bromann** [comment]
@kopax-polyconseil how is your question related to the issue?

**Comment by kopax-polyconseil** [comment]
Sorry duplicate of https://github.com/webdriverio/appium-boilerplate/issues/139 , I close this one
