### ISSUE TITLE
ios app unit tests fail mainly due to webview

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/appium-boilerplate#139]
**Environment (please complete the following information):**
 - Node.js version: v18.7.0
 - NPM version: yarn 1.22.15
 - Platform: iOS
 - Platform version: iOS 15.2
 - Emulator/Simulator/Real Device: Simulator

**Describe the bug**

Test does not pass in CI

```
[0-8] 2022-11-09T14:18:06.559Z INFO webdriver: RESULT [ 'NATIVE_APP' ]
[0-8] Error in "WebdriverIO and Appium, when interacting with a webview through XPATH.should be able to verify that the WebView is shown by switching to the WebView"
Error: Webview context not loaded
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebViewScreen.waitForWebViewContextLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:26:9)
    at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.webview.xpath.spec.ts:30:9)
[0-8] 2022-11-09T14:18:06.868Z INFO webdriver: COMMAND deleteSession()
[0-8] 2022-11-09T14:18:06.868Z INFO webdriver: [DELETE] http://localhost:4723/session/26e14293-d86d-450e-831d-b163548c9731
2022-11-09T14:18:08.119Z DEBUG @wdio/local-runner: Runner 0-8 finished with exit code 1
[0-8] FAILED in iOS - /e2e/tests/specs/app.webview.xpath.spec.ts
2022-11-09T14:18:08.119Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-11-09T14:18:08.119Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-11-09T14:18:08.119Z INFO @wdio/cli:launcher: Run onComplete hook
2022-11-09T14:18:08.120Z DEBUG @wdio/appium-service: Appium (pid: 4497) killed
2022-11-09T14:18:08.120Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

 "spec" Reporter:
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-0] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-0] Session ID: b653b9e4-38c2-4a84-9b09-90b2b411fcf5
[iPhone 13 iOS 15.2 #0-0]
[iPhone 13 iOS 15.2 #0-0] » /e2e/tests/specs/app.biometric.login.spec.ts
[iPhone 13 iOS 15.2 #0-0] WebdriverIO and Appium, when interacting with a biometric button,
[iPhone 13 iOS 15.2 #0-0]    ✓ should be able to login with a matching touch/faceID/fingerprint
[iPhone 13 iOS 15.2 #0-0]    ✖ should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 13 iOS 15.2 #0-0]
[iPhone 13 iOS 15.2 #0-0] 1 passing (32.8s)
[iPhone 13 iOS 15.2 #0-0] 1 failing
[iPhone 13 iOS 15.2 #0-0]
[iPhone 13 iOS 15.2 #0-0] 1) WebdriverIO and Appium, when interacting with a biometric button, should NOT be able to login with a non matching touch/faceID/fingerprint
[iPhone 13 iOS 15.2 #0-0] An attempt was made to operate on a modal dialog when one was not open
[iPhone 13 iOS 15.2 #0-0] no such alert: An attempt was made to operate on a modal dialog when one was not open
[iPhone 13 iOS 15.2 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 13 iOS 15.2 #0-0]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.biometric.login.spec.ts:66:26)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-1] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-1] Session ID: 59dd5ec2-9ff9-4648-b365-4a204fbf13cc
[iPhone 13 iOS 15.2 #0-1]
[iPhone 13 iOS 15.2 #0-1] » /e2e/tests/specs/app.deep.link.navigation.spec.ts
[iPhone 13 iOS 15.2 #0-1] WebdriverIO and Appium, when navigating by deep link
[iPhone 13 iOS 15.2 #0-1]    ✖ should be able to open the webview
[iPhone 13 iOS 15.2 #0-1]    ✓ should be able to open the login form screen
[iPhone 13 iOS 15.2 #0-1]    ✓ should be able to open the forms screen
[iPhone 13 iOS 15.2 #0-1]    ✓ should be able to open the swipe screen
[iPhone 13 iOS 15.2 #0-1]    ✓ should be able to open the drag and drop screen
[iPhone 13 iOS 15.2 #0-1]    ✓ should be able to open the home screen
[iPhone 13 iOS 15.2 #0-1]
[iPhone 13 iOS 15.2 #0-1] 5 passing (1m 23.1s)
[iPhone 13 iOS 15.2 #0-1] 1 failing
[iPhone 13 iOS 15.2 #0-1]
[iPhone 13 iOS 15.2 #0-1] 1) WebdriverIO and Appium, when navigating by deep link should be able to open the webview
[iPhone 13 iOS 15.2 #0-1] Webview context not loaded
[iPhone 13 iOS 15.2 #0-1] Error: Webview context not loaded
[iPhone 13 iOS 15.2 #0-1]     at async WebViewScreen.waitForWebViewContextLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:26:9)
[iPhone 13 iOS 15.2 #0-1]     at async WebViewScreen.waitForWebsiteLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:80:9)
[iPhone 13 iOS 15.2 #0-1]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.deep.link.navigation.spec.ts:17:9)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-2] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-2] Session ID: 7aedf7d8-e24c-4ea9-91d9-0e9f1bbe5bbc
[iPhone 13 iOS 15.2 #0-2]
[iPhone 13 iOS 15.2 #0-2] » /e2e/tests/specs/app.drag.and.drop.spec.ts
[iPhone 13 iOS 15.2 #0-2] WebdriverIO and Appium, when using drag and drop
[iPhone 13 iOS 15.2 #0-2]    ✓ should be able to solve the puzzle by dragging the pieces into the puzzle
[iPhone 13 iOS 15.2 #0-2]
[iPhone 13 iOS 15.2 #0-2] 1 passing (28.1s)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-3] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-3] Session ID: 7e644bbe-15b5-42ca-ba1e-2b052ffc2819
[iPhone 13 iOS 15.2 #0-3]
[iPhone 13 iOS 15.2 #0-3] » /e2e/tests/specs/app.forms.spec.ts
[iPhone 13 iOS 15.2 #0-3] WebdriverIO and Appium, when interacting with form elements,
[iPhone 13 iOS 15.2 #0-3]    ✓ should be able type in the input and validate the text
[iPhone 13 iOS 15.2 #0-3]    ✓ should be able turn on and off the switch
[iPhone 13 iOS 15.2 #0-3]    ✓ should be able select a value from the select element
[iPhone 13 iOS 15.2 #0-3]    ✓ should be able to open the alert and close it with all 3 buttons
[iPhone 13 iOS 15.2 #0-3]    ✓ should be able to determine that the inactive button is inactive
[iPhone 13 iOS 15.2 #0-3]
[iPhone 13 iOS 15.2 #0-3] 5 passing (33s)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-4] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-4] Session ID: 0923fb42-19a2-4e59-ad94-c52319ddf3db
[iPhone 13 iOS 15.2 #0-4]
[iPhone 13 iOS 15.2 #0-4] » /e2e/tests/specs/app.login.spec.ts
[iPhone 13 iOS 15.2 #0-4] WebdriverIO and Appium, when interacting with a login form,
[iPhone 13 iOS 15.2 #0-4]    ✓ should be able login successfully
[iPhone 13 iOS 15.2 #0-4]    ✓ should be able sign up successfully
[iPhone 13 iOS 15.2 #0-4]
[iPhone 13 iOS 15.2 #0-4] 2 passing (28.9s)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-5] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-5] Session ID: da4cc4db-df35-44d5-af6b-951beccde369
[iPhone 13 iOS 15.2 #0-5]
[iPhone 13 iOS 15.2 #0-5] » /e2e/tests/specs/app.swipe.spec.ts
[iPhone 13 iOS 15.2 #0-5] WebdriverIO and Appium, when using swiping
[iPhone 13 iOS 15.2 #0-5]    ✓ should be able to swipe horizontal by swiping the carousel from left to right
[iPhone 13 iOS 15.2 #0-5]    ✓ should be able to swipe vertical by finding the surprise
[iPhone 13 iOS 15.2 #0-5]
[iPhone 13 iOS 15.2 #0-5] 2 passing (41s)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-6] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-6] Session ID: 69bc6e1b-3d77-417f-8264-e5b1cd7eb3ff
[iPhone 13 iOS 15.2 #0-6]
[iPhone 13 iOS 15.2 #0-6] » /e2e/tests/specs/app.tab.bar.navigation.spec.ts
[iPhone 13 iOS 15.2 #0-6] WebdriverIO and Appium, when using navigation through the tab bar
[iPhone 13 iOS 15.2 #0-6]    ✖ should be able to open the webview
[iPhone 13 iOS 15.2 #0-6]    ✓ should be able to open the login form screen
[iPhone 13 iOS 15.2 #0-6]    ✓ should be able to open the forms screen
[iPhone 13 iOS 15.2 #0-6]    ✓ should be able to open the swipe screen
[iPhone 13 iOS 15.2 #0-6]    ✓ should be able to open the drag and drop screen
[iPhone 13 iOS 15.2 #0-6]    ✓ should be able to open the home screen
[iPhone 13 iOS 15.2 #0-6]
[iPhone 13 iOS 15.2 #0-6] 5 passing (1m 5.3s)
[iPhone 13 iOS 15.2 #0-6] 1 failing
[iPhone 13 iOS 15.2 #0-6]
[iPhone 13 iOS 15.2 #0-6] 1) WebdriverIO and Appium, when using navigation through the tab bar should be able to open the webview
[iPhone 13 iOS 15.2 #0-6] Webview context not loaded
[iPhone 13 iOS 15.2 #0-6] Error: Webview context not loaded
[iPhone 13 iOS 15.2 #0-6]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 13 iOS 15.2 #0-6]     at async WebViewScreen.waitForWebViewContextLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:26:9)
[iPhone 13 iOS 15.2 #0-6]     at async WebViewScreen.waitForWebsiteLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:80:9)
[iPhone 13 iOS 15.2 #0-6]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.tab.bar.navigation.spec.ts:16:9)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-7] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-7] Session ID: 5e15b80c-5747-496a-9f0a-52b6da99840b
[iPhone 13 iOS 15.2 #0-7]
[iPhone 13 iOS 15.2 #0-7] » /e2e/tests/specs/app.webview.spec.ts
[iPhone 13 iOS 15.2 #0-7] WebdriverIO and Appium, when interacting with a WebView,
[iPhone 13 iOS 15.2 #0-7]    ? should be able to switch between webview, native and webview
[iPhone 13 iOS 15.2 #0-7]    ✖ "before each" hook for WebdriverIO and Appium, when interacting with a WebView,
[iPhone 13 iOS 15.2 #0-7]
[iPhone 13 iOS 15.2 #0-7] 1 failing (26s)
[iPhone 13 iOS 15.2 #0-7]
[iPhone 13 iOS 15.2 #0-7] 1) WebdriverIO and Appium, when interacting with a WebView, "before each" hook for WebdriverIO and Appium, when interacting with a WebView,
[iPhone 13 iOS 15.2 #0-7] Website not loaded
[iPhone 13 iOS 15.2 #0-7] Error: Website not loaded
[iPhone 13 iOS 15.2 #0-7]     at async WebViewScreen.waitForDocumentFullyLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:62:9)
[iPhone 13 iOS 15.2 #0-7]     at async WebViewScreen.waitForWebsiteLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:82:9)
[iPhone 13 iOS 15.2 #0-7]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.webview.spec.ts:18:9)
------------------------------------------------------------------
[iPhone 13 iOS 15.2 #0-8] Running: iPhone 13 on iOS 15.2 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/iOS-Simulator-NativeDemoApp-0.4.0.app.zip
[iPhone 13 iOS 15.2 #0-8] Session ID: 26e14293-d86d-450e-831d-b163548c9731
[iPhone 13 iOS 15.2 #0-8]
[iPhone 13 iOS 15.2 #0-8] » /e2e/tests/specs/app.webview.xpath.spec.ts
[iPhone 13 iOS 15.2 #0-8] WebdriverIO and Appium, when interacting with a webview through XPATH
[iPhone 13 iOS 15.2 #0-8]    ✓ should be able to verify that the WebView is shown by xpath
[iPhone 13 iOS 15.2 #0-8]    ✖ should be able to verify that the WebView is shown by switching to the WebView
[iPhone 13 iOS 15.2 #0-8]
[iPhone 13 iOS 15.2 #0-8] 1 passing (1m 15.5s)
[iPhone 13 iOS 15.2 #0-8] 1 failing
[iPhone 13 iOS 15.2 #0-8]
[iPhone 13 iOS 15.2 #0-8] 1) WebdriverIO and Appium, when interacting with a webview through XPATH should be able to verify that the WebView is shown by switching to the WebView
[iPhone 13 iOS 15.2 #0-8] Webview context not loaded
[iPhone 13 iOS 15.2 #0-8] Error: Webview context not loaded
[iPhone 13 iOS 15.2 #0-8]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[iPhone 13 iOS 15.2 #0-8]     at async WebViewScreen.waitForWebViewContextLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:26:9)
[iPhone 13 iOS 15.2 #0-8]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.webview.xpath.spec.ts:30:9)


Spec Files:	 4 passed, 5 failed, 9 total (100% completed) in 00:13:12 
```

**To Reproduce**

See actions : https://github.com/pass-culture/pass-culture-app-native/actions/runs/3428740309/workflow

**Comment by christian-bromann** [comment]
@kopax-polyconseil thanks for your investigations. I will go ahead and close this as we are updating the code base and likely run into new/different issues on the way. Hopefully we have a working boilerplate again soon.
