### ISSUE TITLE
android app unit tests fail mainly due to webview

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/appium-boilerplate#140]
**Environment (please complete the following information):**
 - Node.js version: v18.7.0
 - NPM version: yarn 1.22.15
 - Platform: [e.g. Android] Android
 - Platform version: iOS 15.2
 - Emulator/Simulator/Real Device: Emulator

**Describe the bug**

Test does not pass in CI

```
2022-11-09T15:33:45.234Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

 "spec" Reporter:
------------------------------------------------------------------
[emulator-5554 Android 10 #0-1] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-1] Session ID: b590ee4c-39cd-40d6-9b2f-3fa6a9f2011b
[emulator-5554 Android 10 #0-1]
[emulator-5554 Android 10 #0-1] » /e2e/tests/specs/app.deep.link.navigation.spec.ts
[emulator-5554 Android 10 #0-1] WebdriverIO and Appium, when navigating by deep link
[emulator-5554 Android 10 #0-1]    ✖ should be able to open the webview
[emulator-5554 Android 10 #0-1]    ? should be able to open the login form screen
[emulator-5554 Android 10 #0-1]    ✖ "before each" hook for WebdriverIO and Appium, when navigating by deep link
[emulator-5554 Android 10 #0-1]
[emulator-5554 Android 10 #0-1] 2 failing (1m 24.1s)
[emulator-5554 Android 10 #0-1]
[emulator-5554 Android 10 #0-1] 1) WebdriverIO and Appium, when navigating by deep link should be able to open the webview
[emulator-5554 Android 10 #0-1] Website not loaded
[emulator-5554 Android 10 #0-1] Error: Website not loaded
[emulator-5554 Android 10 #0-1]     at async WebViewScreen.waitForDocumentFullyLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:62:9)
[emulator-5554 Android 10 #0-1]     at async WebViewScreen.waitForWebsiteLoaded (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/helpers/WebView.ts:82:9)
[emulator-5554 Android 10 #0-1]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.deep.link.navigation.spec.ts:17:9)
[emulator-5554 Android 10 #0-1]
[emulator-5554 Android 10 #0-1] 2) WebdriverIO and Appium, when navigating by deep link "before each" hook for WebdriverIO and Appium, when navigating by deep link
[emulator-5554 Android 10 #0-1] invalid argument: Unsupported locator strategy: accessibility id
  (Session info: chrome=74.0.3729.185)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.16.0 x86_64)
[emulator-5554 Android 10 #0-1] invalid argument: invalid argument: Unsupported locator strategy: accessibility id
[emulator-5554 Android 10 #0-1]   (Session info: chrome=74.0.3729.185)
[emulator-5554 Android 10 #0-1]   (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.16.0 x86_64)
[emulator-5554 Android 10 #0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[emulator-5554 Android 10 #0-1]     at async Context.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.deep.link.navigation.spec.ts:12:9)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-2] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-2] Session ID: 014fc1d2-5cd3-4d21-8960-62b429131717
[emulator-5554 Android 10 #0-2]
[emulator-5554 Android 10 #0-2] » /e2e/tests/specs/app.drag.and.drop.spec.ts
[emulator-5554 Android 10 #0-2] WebdriverIO and Appium, when using drag and drop
[emulator-5554 Android 10 #0-2]    ✓ should be able to solve the puzzle by dragging the pieces into the puzzle
[emulator-5554 Android 10 #0-2]
[emulator-5554 Android 10 #0-2] 1 passing (1m 30.4s)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-3] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-3] Session ID: 8f2cb678-0ed8-4282-a29f-3c7001831e23
[emulator-5554 Android 10 #0-3]
[emulator-5554 Android 10 #0-3] » /e2e/tests/specs/app.forms.spec.ts
[emulator-5554 Android 10 #0-3] WebdriverIO and Appium, when interacting with form elements,
[emulator-5554 Android 10 #0-3]    ✓ should be able type in the input and validate the text
[emulator-5554 Android 10 #0-3]    ✓ should be able turn on and off the switch
[emulator-5554 Android 10 #0-3]    ✓ should be able select a value from the select element
[emulator-5554 Android 10 #0-3]    ✓ should be able to open the alert and close it with all 3 buttons
[emulator-5554 Android 10 #0-3]    ✓ should be able to determine that the inactive button is inactive
[emulator-5554 Android 10 #0-3]
[emulator-5554 Android 10 #0-3] 5 passing (2m 12.6s)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-4] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-4] Session ID: a2317a44-d122-40d4-8b0e-0d6788832c6d
[emulator-5554 Android 10 #0-4]
[emulator-5554 Android 10 #0-4] » /e2e/tests/specs/app.login.spec.ts
[emulator-5554 Android 10 #0-4] WebdriverIO and Appium, when interacting with a login form,
[emulator-5554 Android 10 #0-4]    ✓ should be able login successfully
[emulator-5554 Android 10 #0-4]    ✓ should be able sign up successfully
[emulator-5554 Android 10 #0-4]
[emulator-5554 Android 10 #0-4] 2 passing (1m 8.4s)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-5] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-5] Session ID: a0b43058-f3e3-45c2-a05b-6667fd916f09
[emulator-5554 Android 10 #0-5]
[emulator-5554 Android 10 #0-5] » /e2e/tests/specs/app.swipe.spec.ts
[emulator-5554 Android 10 #0-5] WebdriverIO and Appium, when using swiping
[emulator-5554 Android 10 #0-5]    ✓ should be able to swipe horizontal by swiping the carousel from left to right
[emulator-5554 Android 10 #0-5]    ✓ should be able to swipe vertical by finding the surprise
[emulator-5554 Android 10 #0-5]
[emulator-5554 Android 10 #0-5] 2 passing (2m 42s)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-6] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-6] Session ID: 7514856f-33fd-4378-8546-ecd9fbbeec08
[emulator-5554 Android 10 #0-6]
[emulator-5554 Android 10 #0-6] » /e2e/tests/specs/app.tab.bar.navigation.spec.ts
[emulator-5554 Android 10 #0-6] WebdriverIO and Appium, when using navigation through the tab bar
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the webview
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the login form screen
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the forms screen
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the swipe screen
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the drag and drop screen
[emulator-5554 Android 10 #0-6]    ✓ should be able to open the home screen
[emulator-5554 Android 10 #0-6]
[emulator-5554 Android 10 #0-6] 6 passing (2m 8.5s)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-7] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-7] Session ID: b1da0b2f-6841-4a9c-bc8b-71d5b7c0ea6c
[emulator-5554 Android 10 #0-7]
[emulator-5554 Android 10 #0-7] » /e2e/tests/specs/app.webview.spec.ts
[emulator-5554 Android 10 #0-7] WebdriverIO and Appium, when interacting with a WebView,
[emulator-5554 Android 10 #0-7]    ✖ should be able to switch between webview, native and webview
[emulator-5554 Android 10 #0-7]
[emulator-5554 Android 10 #0-7] 1 failing (4m 20.3s)
[emulator-5554 Android 10 #0-7]
[emulator-5554 Android 10 #0-7] 1) WebdriverIO and Appium, when interacting with a WebView, should be able to switch between webview, native and webview
[emulator-5554 Android 10 #0-7] Timeout of 180000ms exceeded. The execution in the test "WebdriverIO and Appium, when interacting with a WebView, should be able to switch between webview, native and webview" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.webview.spec.ts)
[emulator-5554 Android 10 #0-7] Error: Timeout of 180000ms exceeded. The execution in the test "WebdriverIO and Appium, when interacting with a WebView, should be able to switch between webview, native and webview" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/e2e/tests/specs/app.webview.spec.ts)
[emulator-5554 Android 10 #0-7]     at createTimeoutError (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/node_modules/mocha/lib/errors.js:498:15)
[emulator-5554 Android 10 #0-7]     at Test.Runnable._timeoutError (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/node_modules/mocha/lib/runnable.js:431:10)
[emulator-5554 Android 10 #0-7]     at Timeout.<anonymous> (/Users/runner/work/pass-culture-app-native/pass-culture-app-native/node_modules/mocha/lib/runnable.js:246:24)
[emulator-5554 Android 10 #0-7]     at listOnTimeout (node:internal/timers:564:17)
[emulator-5554 Android 10 #0-7]     at processTimers (node:internal/timers:507:7)
------------------------------------------------------------------
[emulator-5554 Android 10 #0-8] Running: emulator-5554 on Android 10 executing /Users/runner/work/pass-culture-app-native/pass-culture-app-native/apps/Android-NativeDemoApp-0.4.0.apk
[emulator-5554 Android 10 #0-8] Session ID: c555afb9-1722-4966-8b78-66c58287a2ba
[emulator-5554 Android 10 #0-8]
[emulator-5554 Android 10 #0-8] » /e2e/tests/specs/app.webview.xpath.spec.ts
[emulator-5554 Android 10 #0-8] WebdriverIO and Appium, when interacting with a webview through XPATH
[emulator-5554 Android 10 #0-8]    ✓ should be able to verify that the WebView is shown by xpath
[emulator-5554 Android 10 #0-8]    ✓ should be able to verify that the WebView is shown by switching to the WebView
[emulator-5554 Android 10 #0-8]
[emulator-5554 Android 10 #0-8] 2 passing (1m 1.3s)


Spec Files:	 6 passed, 3 failed, 9 total (100% completed) in 00:27:43 
```

**To Reproduce**

See action https://github.com/pass-culture/pass-culture-app-native/actions/runs/3428737070/workflow

**Expected behavior**

I expect step to work

**Comment by christian-bromann** [comment]
@kopax-polyconseil thanks for your investigations. I will go ahead and close this as we are updating the code base and likely run into new/different issues on the way. Hopefully we have a working boilerplate again soon.
