### ISSUE TITLE
getAlertText() not work with faceID not matching 

### ISSUE THREAD

**Issue by supertgtline** [webdriverio/appium-boilerplate#147]
**Environment (please complete the following information):**
 - Node.js version: 16
 - NPM version: 8
 - Platform: iOS
 - Platform version: 15.2 & 16
 - Emulator/

**Describe the bug**
A getAlertText() not work in case face ID failed. No such alert

**To Reproduce**
Running npm run ios.app -- --spec=tests/specs/app.biometric.login.spec.ts

**Expected behavior**
Allow getTextAlert from that.
**Screenshots**
![image](https://user-images.githubusercontent.com/5604948/207990759-bf393464-96bf-4b63-8210-a8caeecc0faf.png)

[0-0] no such alert in "WebdriverIO and Appium, when interacting with a biometric button,.should NOT be able to login with a non matching touch/faceID/fingerprint"
no such alert: An attempt was made to operate on a modal dialog when one was not open
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Context.<anonymous> (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/tests/specs/app.biometric.login.spec.ts:60:26)
[0-0] 2022-12-15T23:23:36.356Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-12-15T23:23:36.356Z INFO webdriver: [DELETE] http://localhost:4723/session/84f1d39b-840c-48cf-93ae-90d174bafac4
[0-0] 2022-12-15T23:23:36.370Z DEBUG webdriver: request failed due to response error: invalid session id
[0-0] 2022-12-15T23:23:36.370Z WARN webdriver: Request failed with status 404 due to A session is either terminated or not started
[0-0] 2022-12-15T23:23:36.370Z INFO webdriver: Retrying 1/3
[0-0] 2022-12-15T23:23:36.370Z INFO webdriver: [DELETE] http://localhost:4723/session/84f1d39b-840c-48cf-93ae-90d174bafac4
[0-0] 2022-12-15T23:23:36.374Z DEBUG webdriver: request failed due to response error: invalid session id
[0-0] 2022-12-15T23:23:36.374Z WARN webdriver: Request failed with status 404 due to A session is either terminated or not started
[0-0] 2022-12-15T23:23:36.374Z INFO webdriver: Retrying 2/3
[0-0] 2022-12-15T23:23:36.374Z INFO webdriver: [DELETE] http://localhost:4723/session/84f1d39b-840c-48cf-93ae-90d174bafac4
[0-0] 2022-12-15T23:23:36.377Z DEBUG webdriver: request failed due to response error: invalid session id
[0-0] 2022-12-15T23:23:36.377Z WARN webdriver: Request failed with status 404 due to A session is either terminated or not started
[0-0] 2022-12-15T23:23:36.377Z INFO webdriver: Retrying 3/3
[0-0] 2022-12-15T23:23:36.377Z INFO webdriver: [DELETE] http://localhost:4723/session/84f1d39b-840c-48cf-93ae-90d174bafac4
[0-0] 2022-12-15T23:23:36.380Z DEBUG webdriver: request failed due to response error: invalid session id
[0-0] 2022-12-15T23:23:36.380Z ERROR webdriver: Request failed with status 404 due to invalid session id: A session is either terminated or not started
[0-0] 2022-12-15T23:23:36.381Z ERROR @wdio/local-runner: Failed launching test session: invalid session id: A session is either terminated or not started
[0-0]     at getErrorFromResponseBody (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/node_modules/webdriver/build/utils.js:198:12)
[0-0]     at NodeJSRequest._request (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Browser.wrapCommandFn (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Runner.endSession (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/node_modules/@wdio/runner/build/index.js:348:9)
[0-0]     at async Runner.run (/Users/giangthao/Desktop/WorkSpace/Appium/WebdriverIO/appium-simplest/node_modules/@wdio/runner/build/index.js:164:13)

**Comment by wswebcreation** [comment]
Hi @supertgtline 

This is an "issue"/is expected behavior with the "latest" `appium-xcuitest-driver`. I've updated the boilerplate with more explanation of why this is happening and how to overcome this, see [this](https://github.com/webdriverio/appium-boilerplate/blob/main/tests/specs/app.biometric.login.spec.ts#L71) piece of code
