### ISSUE TITLE
Newbie, need some help getting boilerplate to run

### ISSUE THREAD

**Issue by capsizeno4** [webdriverio/appium-boilerplate#30]
**Environment (please complete the following information):**
 - Node.js version:  8.9.1
 - NPM version: 5.8.0
 - Platform: iOS
 - Platform version: 12.2
 - Emulator/Simulator/Real Device: simulator

Hi,

Newbie to webdriverio, I'm having a bit of trouble getting the boilerplate to run.  A little bit of google research tells me this error is saying there is a syntax problem somewhere.  I don't see anything sticking out, was hoping that you might have some insight.

Thanks!

**What I've done:**

- made sure XCode 12.2 simulator is installed
- cloned this repo
- npm install to pull down node_modules
- pulled test .app down, created "apps" directory and dropped it there
- ran npm run ios.app

**What happens:**

```shell
➜ ~/Documents/appium-boilerplate* master npm run ios.app

> appium-boilerplate@5.3.0 ios.app /Users/eharms/Documents/appium-boilerplate
> wdio ./config/wdio.ios.app.conf.js


Execution of 0 spec files started at 2019-08-06T21:23:00.399Z

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.0 ios.app: `wdio ./config/wdio.ios.app.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.3.0 ios.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eharms/.npm/_logs/2019-08-06T21_23_00_433Z-debug.log
```

My wdio.shared.conf.js

```js
exports.config = {
    // ====================
    // Runner and framework
    // Configuration
    // ====================
    runner: 'local',
    framework: 'jasmine',
    jasmineNodeOpts: {
        // Updated the timeout to 30 seconds due to possible longer appium calls
        // When using XPATH
        defaultTimeoutInterval: 90000,
    },
    sync: true,
    logLevel: 'silent',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: [ 'spec' ],

    // ====================
    // Appium Configuration
    // ====================
    services: [ 'appium' ],
    appium: {
        // For options see
        // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        args: {
            // For arguments see
            // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        },
        command: 'appium'
    },

    port: 4723,

    // ====================
    // Some hooks
    // ====================
    beforeSession: (config, capabilities, specs) => {
        require('@babel/register');
    },
};

```

My wdio.ios.app.conf.js

```js
const { config } = require('./wdio.shared.conf');

// ============
// Specs
// ============
config.specs = [
    './tests/specs/**/app*.spec.js',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.desiredCapabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone X',
        'appium:platformVersion': '12.2',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        // The path to the app
        'appium:app': '/Users/eharms/Documents/appium-boilerplate/apps/iOS-Simulator-NativeDemoApp-0.2.1.app',
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        // 'appium:noReset': true,
        // 'appium:newCommandTimeout': 240,
    },
];

exports.config = config;

```

![image](https://user-images.githubusercontent.com/1807520/62579778-7ec5c080-b859-11e9-9256-02dfd75809a4.png)

**Comment by wswebcreation** [comment]
Hi @capsizeno4 

Can you run this test again with the `logLevel:debug` and past the logs here with proper markdown?

**Comment by capsizeno4** [comment]
hi @wswebcreation -- I changed the log level, same result.  Appium is open and listening but you're correct, it's not hitting, no activity in Appium.

[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Would it be possible I can zip up my files so you can have a look locally?

**Comment by capsizeno4** [comment]
Hi, 

just an update.  I started fresh with the webdriverio instructions, and I think I was not using the correct version of node for some of the npm packages.  Ill go ahead and close this one.

Thanks

**Comment by jacquesdev** [comment]
@capsizeno4 - I am in the process of upgrading webdriverio, but must have missed the memo on what key to use in the capabilities object. The example here http://appium.io/docs/en/writing-running-appium/caps/ refers to `{app: 'path'}`, however in your example you have `{'appium:app': 'path'}`, and just wanted to find out how you found out about doing it in that way?

**Comment by wswebcreation** [comment]
@jacquesdev 

`'appium:app'` is the W3C way of setting capabilities, you provide the `{vendorName}:{capability}` structure. You can still use `{app: 'path'}` if you want with Appium

**Comment by jacquesdev** [comment]
@wswebcreation - thank you!

I was trying to upgrade webdriverio from 4 to 5, and when I then tried to define capabilities with app, I was getting feedback that app is not recognised. So I obviously was missing something but wasn't sure what it was.

**Comment by Harsha509** [comment]
@theericharms ,

Can you please let me know what exact node version you've used to resolve the issue ?
Am facing the similar issue with following details

Node.js version: 12.16.0
NPM version: 6.13.4
Platform: iOS
Platform version: 13.7
Emulator/Simulator/Real Device: simulator

Thanks,
Harsha

**Comment by Harsha509** [comment]
Ahh, My bad. Wrong folder name create `app` instead of `apps`. 

Fixed it worked like a charm. loglevel:debug helped to debug issue much faster than browsing things!
