### ISSUE TITLE
error with webdriver when trying to run Appium boilerplate from local machine 

### ISSUE THREAD

**Issue by troyyer** [webdriverio/appium-boilerplate#98]
Hi,

So i've just started playing around with this repos. I was able to run it once on an emulator but now everytime i run it i get the following error 
```
[0-0] 2021-05-06T13:25:13.770Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
    at ClientRequest.<anonymous> (C:\code\appium-boilerplate-main_1\node_modules\got\dist\source\core\index.js:956:111)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (C:\code\appium-boilerplate-main_1\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
[0-0] 2021-05-06T13:25:13.770Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4723/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at Object.startWebDriverSession (C:\code\appium-boilerplate-main_1\node_modules\webdriver\build\utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in Android - C:\code\appium-boilerplate-main_1\tests\specs\app.webview.spec.js
```
I am attempting to run the Android app script using the following command
`npm run android.app`

I have tried to delete the code repo and reinstalling the code but i still get the same issue. I have also restarted my machine. I dont know how to debug this issue. Could someone please assist? I am unsure how to debug the app.

I have only just set up my machine for attempting to test with Mobile devices. Things I have done
On a Windows 10 machine and using VS Code as my IDE

- Installed Android Studio
- Install Java
- install appium globally (`npm install appium -g`)
- install appium doctor (`npm install appium-doctor -g`)
- download webdriverIO appium-boilerplate 
- once downloaded and extracted, run `npm install`

**Environment:**
 - Node.js version: v12.16.1
 - NPM version: 6.13.4
 - Platform: Android
 - Platform version: 11
 - Emulator/Simulator/Real Device: Emulator

**Additional context**
config in **wdio.android.app.conf.js**
```
const { join } = require('path');
const { config } = require('./wdio.shared.conf');
config.specs = [
    './tests/specs/**/app.webview.spec.js',
];
config.capabilities = [
    {
        platformName: 'Android',
        maxInstances: 1,
        'appium:deviceName': 'Pixel_3a_API_30_x86',
        'appium:platformVersion': '11',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        'appium:app': join(process.cwd(), './apps/Android-NativeDemoApp-0.2.1.apk'),
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    },
];
exports.config = config;
```
 In VS Code, on the package.json file, I hovered my cursor over 'android.app' and clicked  the "Debug Script" pop up, but it didnt provide anything different

**Comment by christian-bromann** [comment]
> RequestError: connect ECONNREFUSED 127.0.0.1:4723

It seems like you haven't started Appium. You might want to give `@wdio/appium-service` a try.

**Comment by troyyer** [comment]
hi @christian-bromann , 
when you say give '@wdio/appium-service' a try, what exactly do you mean?
I hadn't changed how i ran the script when it worked the first time. Doesn't it run the appium as part of the script?
apologies but i also see the follow errors in the terminal window
```
2021-05-06T13:45:49.256Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 2)
Debugg
2021-05-06T13:45:49.258Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 2)
Debugg
    at ChildProcess.<anonymous> (C:\code\appium-boilerplate-main_1\node_modules\@wdio\appium-service\build\launcher.js:80:22)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Continue...
```

**Comment by christian-bromann** [comment]
It seems Appium can't be run due to an issue. Can you debug what happens in during launch? Maybe something is coming from stderr?

**Comment by troyyer** [comment]
Apologies but what command do i have to perform/run to debug it during launch?

**Comment by christian-bromann** [comment]
You put some `console.logs` somewhere around `C:\code\appium-boilerplate-main_1\node_modules\@wdio\appium-service\build\launcher.js:80`.

**Comment by troyyer** [comment]
so on line 80 of the file is currently 
` callback(new Error(errorMessage), null);`
should i change this to 
 callback(new Error(console.log(errorMessage)), null);
?

**Comment by troyyer** [comment]
Sorry I'm still unable to figure out how to debug this and provide further logs. Any assistance with this would be greatly appreciated.

**Comment by troyyer** [comment]
I have also tried uninstalling appium without any success
```
npm uninstall appium -g
npm uninstall appium
```
restarted my machine 
opened my bolierplate project and ran the commands to install appium
```
npm install appium -g
npm install appium
```
once installed, i tried to run the spec file again
 `npm run android.app` 
execution still faild
```
C:\code\appium-boilerplate-main_1>npm run android.app

> appium-boilerplate@5.3.1 android.app C:\code\appium-boilerplate-main_1
> wdio ./config/wdio.android.app.conf.js

2021-05-06T23:34:55.060Z DEBUG @wdio/config:utils: Couldn't find ts-node package, no TypeScript compiling

Execution of 1 spec files started at 2021-05-06T23:34:55.374Z

2021-05-06T23:34:55.499Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-05-06T23:35:17.786Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 2)
usage: C:\Users\joparel\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
       [-h] [--shell] [--allow-cors] [--reboot] [--ipa IPA] [-a ADDRESS]
       [-p PORT] [-pa BASEPATH] [-ka KEEPALIVETIMEOUT] [-ca CALLBACKADDRESS]
       [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT] [-r BACKENDRETRIES]
       [--session-override] [-l] [-g LOGFILE]
       [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
       [--log-timestamp] [--local-timezone] [--log-no-colors] [-G WEBHOOK]
       [--safari] [--default-device] [--force-iphone] [--force-ipad]
       [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
       [--instruments INSTRUMENTSPATH] [--nodeconfig NODECONFIG]
       [-ra ROBOTADDRESS] [-rp ROBOTPORT]
       [--chromedriver-executable CHROMEDRIVEREXECUTABLE] [--show-config]
       [--no-perms-check] [--strict-caps] [--isolate-sim-device]
       [--tmp TMPDIR] [--trace-dir TRACEDIR] [--debug-log-spacing]
       [--suppress-adb-kill-server] [--long-stacktrace]
       [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT]
       [--webdriveragent-port WDALOCALPORT] [-dc DEFAULTCAPABILITIES]
       [--relaxed-security] [--allow-insecure ALLOWINSECURE]
       [--deny-insecure DENYINSECURE]
       [--command-timeout DEFAULTCOMMANDTIMEOUT] [-k]
       [--platform-name PLATFORMNAME] [--platform-version PLATFORMVERSION]
       [--automation-name AUTOMATIONNAME] [--device-name DEVICENAME]
       [--browser-name BROWSERNAME] [--app APP] [-lt LAUNCHTIMEOUT]
       [--language LANGUAGE] [--locale LOCALE] [-U UDID]
       [--orientation ORIENTATION] [--no-reset] [--full-reset]
       [--app-pkg APPPACKAGE] [--app-activity APPACTIVITY]
       [--app-wait-package APPWAITPACKAGE]
       [--app-wait-activity APPWAITACTIVITY]
       [--device-ready-timeout DEVICEREADYTIMEOUT]
       [--android-coverage ANDROIDCOVERAGE] [--avd AVD] [--avd-args AVDARGS]
       [--use-keystore] [--keystore-path KEYSTOREPATH]
       [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
       [--key-password KEYPASSWORD] [--intent-action INTENTACTION]
       [--intent-category INTENTCATEGORY] [--intent-flags INTENTFLAGS]
       [--intent-args OPTIONALINTENTARGUMENTS] [--dont-stop-app-on-reset]
       [--calendar-format CALENDARFORMAT] [--native-instruments-lib]
       [--keep-keychains] [--localizable-strings-dir LOCALIZABLESTRINGSDIR]
       [--show-ios-log] [--async-trace] [--chromedriver-port CHROMEDRIVERPORT]
       [--log-filters LOGFILTERS] [-v]

2021-05-06T23:35:17.791Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 2)
usage: C:\Users\joparel\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
       [-h] [--shell] [--allow-cors] [--reboot] [--ipa IPA] [-a ADDRESS]
       [-p PORT] [-pa BASEPATH] [-ka KEEPALIVETIMEOUT] [-ca CALLBACKADDRESS]
       [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT] [-r BACKENDRETRIES]
       [--session-override] [-l] [-g LOGFILE]
       [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
       [--log-timestamp] [--local-timezone] [--log-no-colors] [-G WEBHOOK]
       [--safari] [--default-device] [--force-iphone] [--force-ipad]
       [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
       [--instruments INSTRUMENTSPATH] [--nodeconfig NODECONFIG]
       [-ra ROBOTADDRESS] [-rp ROBOTPORT]
       [--chromedriver-executable CHROMEDRIVEREXECUTABLE] [--show-config]
       [--no-perms-check] [--strict-caps] [--isolate-sim-device]
       [--tmp TMPDIR] [--trace-dir TRACEDIR] [--debug-log-spacing]
       [--suppress-adb-kill-server] [--long-stacktrace]
       [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT]
       [--webdriveragent-port WDALOCALPORT] [-dc DEFAULTCAPABILITIES]
       [--relaxed-security] [--allow-insecure ALLOWINSECURE]
       [--deny-insecure DENYINSECURE]
       [--command-timeout DEFAULTCOMMANDTIMEOUT] [-k]
       [--platform-name PLATFORMNAME] [--platform-version PLATFORMVERSION]
       [--automation-name AUTOMATIONNAME] [--device-name DEVICENAME]
       [--browser-name BROWSERNAME] [--app APP] [-lt LAUNCHTIMEOUT]
       [--language LANGUAGE] [--locale LOCALE] [-U UDID]
       [--orientation ORIENTATION] [--no-reset] [--full-reset]
       [--app-pkg APPPACKAGE] [--app-activity APPACTIVITY]
       [--app-wait-package APPWAITPACKAGE]
       [--app-wait-activity APPWAITACTIVITY]
       [--device-ready-timeout DEVICEREADYTIMEOUT]
       [--android-coverage ANDROIDCOVERAGE] [--avd AVD] [--avd-args AVDARGS]
       [--use-keystore] [--keystore-path KEYSTOREPATH]
       [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
       [--key-password KEYPASSWORD] [--intent-action INTENTACTION]
       [--intent-category INTENTCATEGORY] [--intent-flags INTENTFLAGS]
       [--intent-args OPTIONALINTENTARGUMENTS] [--dont-stop-app-on-reset]
       [--calendar-format CALENDARFORMAT] [--native-instruments-lib]
       [--keep-keychains] [--localizable-strings-dir LOCALIZABLESTRINGSDIR]
       [--show-ios-log] [--async-trace] [--chromedriver-port CHROMEDRIVERPORT]
       [--log-filters LOGFILTERS] [-v]

    at ChildProcess.<anonymous> (C:\code\appium-boilerplate-main_1\node_modules\@wdio\appium-service\build\launcher.js:80:22)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Continue...
2021-05-06T23:35:17.804Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-05-06T23:35:17.817Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./config/wdio.android.app.conf.js
[0-0] 2021-05-06T23:35:24.280Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in Android - C:\code\appium-boilerplate-main_1\tests\specs\app.webview.spec.js
[0-0] 2021-05-06T23:35:32.643Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-05-06T23:35:32.649Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2021-05-06T23:35:32.650Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      'appium:deviceName': 'Pixel_3a_API_30_x86',
      'appium:platformVersion': '11',
      'appium:orientation': 'PORTRAIT',
      'appium:automationName': 'UiAutomator2',
      'appium:app': 'C:\\code\\appium-boilerplate-main_1\\apps\\Android-NativeDemoApp-0.2.1.apk',
      'appium:noReset': true,
      'appium:newCommandTimeout': 240
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    'appium:deviceName': 'Pixel_3a_API_30_x86',
    'appium:platformVersion': '11',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'UiAutomator2',
    'appium:app': 'C:\\code\\appium-boilerplate-main_1\\apps\\Android-NativeDemoApp-0.2.1.apk',
    'appium:noReset': true,
    'appium:newCommandTimeout': 240
  }
}
[0-0] 2021-05-06T23:35:33.951Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
    at ClientRequest.<anonymous> (C:\code\appium-boilerplate-main_1\node_modules\got\dist\source\core\index.js:956:111)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (C:\code\appium-boilerplate-main_1\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
[0-0] 2021-05-06T23:35:33.952Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4723/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at Object.startWebDriverSession (C:\code\appium-boilerplate-main_1\node_modules\webdriver\build\utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in Android - C:\code\appium-boilerplate-main_1\tests\specs\app.webview.spec.js
2021-05-06T23:35:34.614Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:39

2021-05-06T23:35:34.621Z INFO @wdio/local-runner: Shutting down spawned worker
2021-05-06T23:35:34.875Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-05-06T23:35:34.881Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-boilerplate@5.3.1 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joparel\AppData\Roaming\npm-cache\_logs\2021-05-06T23_35_36_116Z-debug.log
```

**Comment by christian-bromann** [comment]
It is hard to say what is going on here, can you provide a minimal reproducible exampel?

**Comment by troyyer** [comment]
well all i've done with regard to this project is download the repos as a zip file, extracted into my code folder, then added in the **apps** folder and placed the webdriverio android app, and then updated 2 of the config files
update the **wdio.shared.conf.js** file with 
```
exports.config = {
    runner: 'local',
    framework: 'jasmine',
    hostname: 'localhost',
    path: '/wd/hub',
    jasmineNodeOpts: {
        defaultTimeoutInterval: 90000,
        helpers: [require.resolve('@babel/register')],
    },
    sync: true,
    logLevel: 'info',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: ['spec'],

    services: [
        [
            'appium',
            {
               args: {
                    relaxedSecurity: true,
                     chromedriverAutodownload: true,
                     debugLogSpacing: true,
                },
                command: 'appium --allow-insecure chromedriver_autodownload',
                logPath : './',
                path: '/wd/hub',
            },
        ],
    ],
    port: 4723,
};
```
and update the **wdio.android.app.conf.js** file with 

```
const { join } = require('path');
const { config } = require('./wdio.shared.conf');

config.specs = [
    './tests/specs/**/app.webview.spec.js',
];

config.capabilities = [
    {
        platformName: 'Android',
        maxInstances: 1,
        'appium:deviceName': 'Pixel_3a_API_30_x86',
        'appium:platformVersion': '11',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        'appium:app': join(process.cwd(), './apps/Android-NativeDemoApp-0.2.1.apk'),
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    },
    
];

exports.config = config;
```

once copied and saved i ran **npm install**
once the install is completed i ran **npm run android.app**
it's definitely something that i've done on my machine but i'm unsure what it is I did and i'm not sure how to provide/capture further log. I've tried to follow what is mentioned here in the following ticket https://github.com/webdriverio/appium-boilerplate/issues/87 but it didnt change the error message.

**Comment by christian-bromann** [comment]
> `command: 'appium --allow-insecure chromedriver_autodownload',`

You are not suppose to have parameters in the command option. That what `args` is for.

**Comment by troyyer** [comment]
so in wdio.shared.conf.js i've changed this back to 
`                command: 'appium',`
I reran **npm run android.app** but i still got the same error message as before 

```
[0-0] 2021-05-07T07:54:11.066Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
    at ClientRequest.<anonymous> (C:\code\appium-boilerplate-main_1\node_modules\got\dist\source\core\index.js:956:111)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (C:\code\appium-boilerplate-main_1\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
[0-0] 2021-05-07T07:54:11.067Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4723/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at Object.startWebDriverSession (C:\code\appium-boilerplate-main_1\node_modules\webdriver\build\utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in Android - C:\code\appium-boilerplate-main_1\tests\specs\app.webview.spec.js
2021-05-07T07:54:11.383Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:15

2021-05-07T07:54:11.385Z INFO @wdio/local-runner: Shutting down spawned worker
2021-05-07T07:54:11.638Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-05-07T07:54:11.639Z INFO @wdio/local-runner: shutting down
```
